version: '3.8'
services:
  web:
    build: .
    container_name: 'web'
    ports:
      - '8080:8080'
  database:
    image: 'postgres:13.13'
    container_name: 'database'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=store